### ISSUE TITLE
Using navigate with state object

### ISSUE THREAD

**Issue by supermensa** [baseprime/grapnel#19]
If have a case where I need to send a state obj when calling navigate

example:

```
var stateobj = {modal: true, id: "e943", color: "#333"};
router.navigate("/product.html", stateobj);
```

I'd also like to process this state object inside my 'navigate' event listener.

```
router.on('navigate', function(event){
  // process stateobj here, open modal or whatever
});
```

Is this possible somehow - or would you consider such an enhancement?

**Comment by Nicolab** [comment]
I propose the name "context" instead of "state". 
"State" is too specific to a state, context is generic and is the name used in other routers.

No?

**Comment by supermensa** [comment]
As far as I can see, Grapnel only uses ```History.pushState```with an empty object as state argument.

I'd like to enable the use of the browser's back button, so the router will use the saved state object if one is available in the history.

**Comment by Nicolab** [comment]
Ok, indeed it's very useful

**Comment by supermensa** [comment]
Question is if Grapnel should support this? I think it would be the feature that would make it a perfect JS router.

Right now, I guess it is possible to do something like this, but seems a little stupid.
```
var stateobj = {modal: true, id: "e943", color: "#333"};

// state, not url here
window.history.pushState(stateobj, null, null);

router.navigate("/product.html");

// listen to history popstate
window.onpopstate = function (event) {
      console.log(event.state) // {modal: true, id: "e943", color: "#333"};
}
```

but it would be nice if the state object could be used as an optional argument with Graphnel's ```navigate``` method. Looking at alternative routers, I wonder if it's not easier to always use an object with navigate. Like this:

```
router.navigate({
 // url required
  url: "/product.html",
 // all these are optional
  state: {modal: true, id: "e943", color: "#333"},
  title: "Product",
  trigger: true,
  replace: false
});
```
