### ISSUE TITLE
Feature Request : options.root applicable for hashbang urls too

### ISSUE THREAD

**Issue by Chandu** [baseprime/grapnel#38]
Thanks for the simple/awesome router.

I looked at the documentation/code and realized that the options.root is only applicable for the pushState mode.

Can this be made applicable to the regular non pushState mode too?

I am aware that router.context(), can help me here, router.context returns only a wrapper to router.get.

I think that the frag.get/set methods needs to be changed to use the options.root for the non pushState mode, but am not good with the pushState/JS tests and don't want to waste your time sending a pull request without test coverage :(

**Comment by slier81** [comment]
On line 244 [https://github.com/baseprime/grapnel/blob/master/src/grapnel.js#L244](url) replace with following code:

```
if (root.location.hash) {
	frag = root.location.hash.split((self.options.hashBang ? '#!' : '#'))[1]
}
else {
	root.location.hash = (self.options.root) ? self.options.root : '#/';
	frag = root.location.hash.split((self.options.hashBang ? '#!' : '#'))[1]
}
```
