### ISSUE TITLE
an `.off` method to unregister an event listener

### ISSUE THREAD

**Issue by mhelvens** [baseprime/grapnel#44]
If your interface has an `.on` method to register event listeners, it really should support some way to _unregister_ them. And to be consistent with expectations, this should be `.off(event, callback)`.

For example, I'm trying to plug the router into a [Kefir](http://pozadi.github.io/kefir/) stream:

``` javascript
Kefir.fromEvents(this.router, 'navigate')
```

But the [`Kefir.fromEvents` ](https://pozadi.github.io/kefir/#from-event) function will throw an error like this:

```
Uncaught Error: target don't support any of addEventListener/removeEventListener, addListener/removeListener, on/off method pair
```

**Comment by creatorrr** [comment]
Progress on this, @bytecipher? Happy to submit a patch for this.
