### ISSUE TITLE
Working with nginx 

### ISSUE THREAD

**Issue by zacharynevin** [baseprime/grapnel#58]
Hello,

How would I get this to work with an nginx static file server, where I don't want hashbangs between navigating. Currently it seems that doing `<a href="/my/route">` triggers the page to actually navigate to that route through nginx.

I should also mention that my nginx is serving from the path `/welcome`:

```
// index.js
<base href="/welcome/">

// router.js
var router = new Grapnel({ root: '/welcome/' })

router
  .get('intro/:step', function (req, e) {
 })

// nginx.conf
location /welcome {
  try_files $uri /index.html;
}
```

**Comment by baseprime** [comment]
If you're setting up a single-page app, this answer might help you: 

http://stackoverflow.com/questions/7027636/nginx-send-all-requests-to-a-single-html-page
