### ISSUE TITLE
Anchor navigation with pushState : true not seems to be working

### ISSUE THREAD

**Issue by pravin-d** [baseprime/grapnel#66]
I'm trying to develop an application with HTML5 push state. Anchor navigation with hash seems to work. However not able to seem to make work with HTML5 push state (maybe  use custom click listener ?)

**Comment by Juul** [comment]
I don't think this is built into grapnel. You can add it with something like:

```
  document.addEventListener('click', function(e) {
    if(e.target.tagName === 'A' && e.target.href && e.target.href !== '#') {
      e.preventDefault();
      router.navigate(e.target.href);
    }
  });
```
