### ISSUE TITLE
How to Init Hash navigation

### ISSUE THREAD

**Issue by pravin-d** [baseprime/grapnel#68]
I'm trying to use the basic hash navigation. However unless I do a router.navigate(''), the router does not get init.
So when I call 
domain.com or domain.com/ it should hit the router and be init-ed to 
domain.com/#/home
Any Idea how to do this ?

**Comment by baseprime** [comment]
For Grapnel to remain unobtrusive, it's up to your app to call `router.navigate()` to initialize subsequent events.
